export const billingCostOptions = [
  { label: 'Billing', value: 'billing' },
  { label: 'Cost', value: 'cost' },
]

export const creditTermOptions = [
  { label: 'At sign', value: 'atsign' },
  { label: '15 days', value: '15days' },
  { label: '30 days', value: '30days' },
  { label: '45 days', value: '45days' },
  { label: '60 days', value: '60days' },
  { label: '90 days', value: '90days' },
  { label: '120 days', value: '120days' },
]

export const paymentTermOptions = [
  { label: 'Collect', value: 'collect' },
  { label: 'Prepaid', value: 'prepaid' },
]

export const billToOptions = [
  { label: 'Employee', value: 'employee' },
  { label: 'Partner', value: 'partner' },
]

export const employeeList = [
  { label: 'Employee 1', value: 'employee1' },
  { label: 'Employee 2', value: 'employee2' },
  { label: 'Employee 3', value: 'employee3' },
  { label: 'Employee 4', value: 'employee4' },
  { label: 'Employee 5', value: 'employee5' },
]

export const partnerList = [
  { label: 'Partner 1', value: 'partner1' },
  { label: 'Partner 2', value: 'partner2' },
  { label: 'Partner 3', value: 'partner3' },
  { label: 'Partner 4', value: 'partner4' },
  { label: 'Partner 5', value: 'partner5' },
]

export const descriptionCodeOptions = [
  { label: 'ACI FEE', value: 'ACI' },
  { label: 'Advance Payment for Carrier', value: 'ADVANCE-CARRIER' },
  { label: 'AFR FEE', value: 'AFR' },
  { label: 'AFS Phụ phí khai báo hải quan Nhật Bản', value: 'AFS' },
  { label: 'AIR CERTIFICATE', value: 'AIR-CERTIFICATE' },
  { label: 'AIR FREIGHT', value: 'AF' },
  { label: 'AIR FREIGHT & EXW-CHARGE', value: 'AF-EXW' },
  { label: 'AIR TICKET/ VÉ MÁY BAY', value: 'AIR-TICKET' },
  { label: 'ALLOWANCE/ PHỤ CẤP', value: 'ALLOWANCE' },
  { label: 'AMENDMENT FEE', value: 'AMEND' },
  { label: 'AMS FEE', value: 'AMS' },
  { label: 'AUTHORIZATION FEE', value: 'UYQUYEN' },
  { label: 'AWB FEE/ Phí bill air', value: 'AWB' },
  { label: 'BANK CHARGE', value: 'BANK-CHARGE' },
  { label: 'Bảo hiểm y tế - Xã hội', value: 'BHYTXH' },
  { label: 'BARGE FEE', value: 'BGF' },
  { label: 'BILL & TELEX', value: 'BL-TLX' },
  { label: 'BONUS - INCENTIVE CHARGE', value: 'BONUS' },
  { label: 'BOOKING FEE', value: 'BOOKING-FEE' },
  { label: 'CERT ISSUE FEE', value: 'CERT-FEE' },
  { label: 'CERTIFICATE OF QUALITY', value: 'CQ' },
  { label: 'CERTIFICATE ORIGINAL FEE', value: 'CO' },
  { label: 'CFS STORAGE', value: 'CFSSTG' },
  { label: 'CHARGE TAX', value: 'CHARGE-TAX' },
  { label: 'CHI HO', value: 'CHIHO' },
  { label: 'CHỨNG NHẬN HỢP QUY', value: 'CHUNGNHANHOPQUY' },
  { label: 'CLEAN TRUCK FEE', value: 'CTF' },
  { label: 'COMMISSION FEE', value: 'COM' },
  { label: 'COMPANY TRIP/ CHI PHÍ DU LỊCH', value: 'TRIP' },
  { label: 'CONTRACT FEE', value: 'CONTRACT' },
  { label: 'COOL CHAIN FEE', value: 'COOL-CHAIN' },
  { label: 'COURIER FEE', value: 'COURIER' },
  { label: 'CRANE(Phí cẩu hàng)', value: 'CRANE' },
  { label: 'CƯỚC VẬN TẢI QUỐC TẾ', value: 'O/F' },
  { label: 'CƯỚC VẬN TẢI QUỐC TẾ & PHỤ PHÍ(OF + EXW)', value: 'O/FEXW' },
  { label: 'CƯỚC VẬN TẢI QUỐC TẾ & PHỤ PHÍ(OF + FCA)', value: 'O/FFCA' },
  { label: 'CUSTOM INSPECTION', value: 'CUS-IS' },
  { label: 'CUSTOMS SUPERVISION', value: 'CUS-SUP' },
  { label: 'CUSTOMS CLEARNACE FEE', value: 'CCL' },
  { label: 'CUSTOM DOCCUMENT FEE', value: 'CUSTOM-DOC' },
  { label: 'CUSTOMS FEE', value: 'CUSTOMS' },
  { label: 'DANGEROUS FEE', value: 'DG-FEE' },
  { label: 'DILIVERY DUTY PAID', value: 'DDP' },
  { label: 'DILIVERY DUTY UNPAID', value: 'DDU' },
  { label: 'DEMURRAGE CHARGE', value: 'DEM' },
  { label: 'DEPOSITE CONTAINER FEE', value: 'DEPOSITE-CONT' },
  { label: 'DEPRECISTION FEE/ CHÊNH LỆCH TỈ GIÁ', value: 'DEPRECISTION' },
  { label: 'DESTINATION DELIVERY CHARGE', value: 'DDC' },
  { label: 'DESTINATION THC', value: 'DTHC' },
  { label: 'ĐỊNH MỨC KIỂM HOÁ', value: 'DMKH' },
  { label: 'ĐỊNH MỨC RÚT RUỘT TẠI CẢNG', value: 'DMRR' },
  { label: 'ĐỊNH MỨC SOI CHIẾU', value: 'DMSC' },
  { label: 'DOCCUMENT FEE', value: 'DOC' },
  { label: 'DOOR DELIVERY CHARGE', value: 'DOOR' },
  { label: 'DUTY & TAX FEE/ THUẾ NHẬP KHẨU', value: 'DUTY-TAX' },
  { label: 'EBS CHARGE', value: 'EBS' },
  { label: 'ELECTRIC FEE/ TIỀN ĐIỆN', value: 'ELECTRIC' },
  { label: 'ENS FEE', value: 'ENS' },
  { label: 'FACILITIES - LOCAL CHARGE', value: 'FACILITIES' },
  { label: 'FREIGHT', value: 'FREIGHT' },
  { label: 'FS CHARGE', value: 'FCS' },
  { label: 'FUEL SURCHARGE', value: 'FUEL' },
  { label: 'FUMIGATION FEE', value: 'FUMI' },
  { label: 'G.O.H FEE', value: 'GOH' },
  { label: 'GATE IN FEE', value: 'GATE-IN' },
  { label: 'GENSET FEE', value: 'GENSET-FEE' },
  { label: 'GIAO NHẬN', value: 'GIAONHAN' },
  { label: 'GIFT FEE/ QUÀ TẶNG', value: 'GIFT' },
  { label: 'GRI', value: 'GRI' },
  { label: 'GIAO NHẬN HÀNG', value: 'GIAONHANHANG' },
]

export const unitPriceOptions = [
  { label: 'USD', value: 'USD' },
  { label: 'VND', value: 'VND' },
  { label: 'RMB', value: 'RMB' },
  { label: 'EUR', value: 'EUR' },
  { label: 'AUD', value: 'AUD' },
  { label: 'BRL', value: 'BRL' },
  { label: 'HKD', value: 'HKD' },
  { label: 'JPY', value: 'JPY' },
  { label: 'GBP', value: 'GBP' },
]

export const chargePerOptions = [
  { label: 'File/Job', value: 'File/Job' },
  { label: 'CBM', value: 'CBM' },
  { label: 'CAV', value: 'CAV' },
  { label: 'CAW', value: 'CAW' },
  { label: 'DO', value: 'DO' },
  { label: 'EACH CTR', value: 'EACH CTR' },
  { label: 'EACH TIME', value: 'EACH TIME' },
  { label: 'GW', value: 'GW' },
  { label: 'MLB/MAWB', value: 'MLB/MAWB' },
  { label: 'Package', value: 'Package' },
  { label: 'Revenue ton', value: 'Revenue ton' },
  { label: 'Shipment', value: 'Shipment' },
  { label: 'Ton', value: 'Ton' },
  { label: '20', value: '20' },
  { label: '20FL', value: '20FL' },
  { label: '20HC', value: '20HC' },
  { label: '20OT', value: '20OT' },
  { label: '20RF', value: '20RF' },
  { label: '40', value: '40' },
  { label: '40FL', value: '40FL' },
  { label: '40GP', value: '40GP' },
  { label: '40HC', value: '40HC' },
  { label: '40OH', value: '40OH' },
  { label: '40OT', value: '40OT' },
  { label: '40RF', value: '40RF' },
  { label: '45', value: '45' },
  { label: '60', value: '60' },
]

export const vatCodeOptions = [
  { label: 'No VAT', value: 'no-vat' },
  { label: 'Include VAT 5.000%', value: 'include-vat-5' },
  { label: 'Include VAT 5.260%', value: 'include-vat-5260' },
  { label: 'Include VAT 8.000%', value: 'include-vat-8' },
  { label: 'Include VAT 10.000%', value: 'include-vat-10' },
  { label: 'Exclude VAT 5.000%', value: 'exclude-vat-5' },
  { label: 'Exclude VAT 5.260%', value: 'exclude-vat-5260' },
  { label: 'Exclude VAT 8.000%', value: 'exclude-vat-8' },
  { label: 'Exclude VAT 10.000%', value: 'exclude-vat-10' },
]

export const allocationTypeOptions = [
  { label: 'Chargeable Volume', value: 'chargeable-volume' },
  { label: 'Chargeable Weight', value: 'chargeable-weight' },
  { label: 'Gross Weight', value: 'gross-weight' },
  { label: "Q'ty of HBL/HAWB/Shipment Note", value: 'hbl-hawb' },
  { label: "Q'ty of package", value: 'qty-package' },
  { label: "Q'ty of TEU", value: 'qty-teu' },
]
